# arxivの学問領域の指定
subject: 'cs.*'

# 検索キーワード
keywords:
    kaggle: 3
    resnet: 3
    health: 10
    anomaly detection: 1
    sound: 1
    audio: 1
    sound feature: 3
    audio feature: 3
    noise removal: 2
    spectrogram: 3
    partial label: 4
    transformer: 5
    gan: 10
    domain shift: 2
    nlp: 3
    partial label: 2
    sentiment: 1
    attention: 12

# 通知の閾値
score_threshold: 0
